# Generated by Django 3.2.15 on 2022-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transaction', '0002_auto_20221001_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
