# Generated by Django 3.2.15 on 2022-10-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transaction', '0003_alter_stockuser_account_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('user', 'stock')},
        ),
    ]
